[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
description = "xml-rs based deserializer for Serde (compatible with 0.9+)"
license = "MIT"
name = "serde-xml-rs"
repository = "https://github.com/RReverser/serde-xml-rs"
version = "0.4.1"

[dependencies]
log = "0.4"
serde = "1.0"
xml-rs = "0.8.0"
thiserror = "1.0"

[dev-dependencies]
serde_derive = "1.0"
simple_logger = "1.0.1"
docmatic = "0.1.2"
serde_json = "1.0"
serde-transcode = "1.1.0"
