[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
description = "xml-rs based deserializer for Serde (compatible with 0.9+)"
license = "MIT"
name = "serde-xml-rs"
repository = "https://github.com/RReverser/serde-xml-rs"
version = "0.3.0"

[dependencies]
log = "0.4"
serde = "1.0"
xml-rs = "0.8.0"
error-chain = { version = "0.10.0", default-features = false }

[dev-dependencies]
serde_derive = "1.0"
simple_logger = "1.0.1"
docmatic = "0.1.2"

[features]
default = ["with-backtrace"]
with-backtrace = ["error-chain/default"]
legacy-support = ["error-chain/example_generated"]
