[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
description = "xml-rs based deserializer for Serde (compatible with 0.9+)"
license = "MIT"
name = "serde-xml-rs"
repository = "https://github.com/RReverser/serde-xml-rs"
version = "0.1.1"

[dependencies]
log = "0.3.6"
serde = "0.9.7"
xml-rs = "0.3.6"

[dev-dependencies]
serde_derive = "0.9.7"
